#!/usr/bin/env bash
# Generate a self-signed TLS certificate and key (with SANs) and install
# environment variables for Uvicorn (system-wide via /etc/profile.d).
#
# Requirements: openssl, sudo privileges
#
# Usage:
#   sudo bash generate_ssl.sh -n <name1[,name2,...]> [-n <nameX>] [-o /etc/ssl/frbot] [-d 825] [-f]
#     -n can be specified multiple times or as a comma-separated list (IPs and/or domains)
#
# Examples:
#   sudo bash generate_ssl.sh -n example.com
#   sudo bash generate_ssl.sh -n 127.0.0.1 -o /etc/ssl/frbot -d 365
#   sudo bash generate_ssl.sh -n "35.74.241.110,18.177.92.181"
#   sudo bash generate_ssl.sh -n 35.74.241.110 -n 18.177.92.181
#
# After running, re-login or run: source /etc/profile.d/uvicorn_ssl.sh

set -euo pipefail

# Collected SAN names (IPs or domains)
NAMES=()
OUT_DIR="/etc/ssl/frbot"
DAYS=825
FORCE=0

usage() {
  echo "Usage: sudo bash $0 -n <name1[,name2,...]> [-n <nameX>] [-o /etc/ssl/frbot] [-d 825] [-f]" 1>&2
  exit 1
}

# Parse arguments
while getopts ":n:o:d:f" opt; do
  case "$opt" in
    n)
      IFS=',' read -r -a parts <<<"$OPTARG"
      for p in "${parts[@]}"; do
        p_trim=$(echo "$p" | xargs)
        if [[ -n "$p_trim" ]]; then
          NAMES+=("$p_trim")
        fi
      done
      ;;
    o) OUT_DIR="$OPTARG" ;;
    d) DAYS="$OPTARG" ;;
    f) FORCE=1 ;;
    *) usage ;;
  esac
done

if [[ ${#NAMES[@]} -eq 0 ]]; then
  echo "[ERROR] At least one -n <domain-or-ip> is required." 1>&2
  usage
fi

# Ensure running with sudo/root
if [[ $EUID -ne 0 ]]; then
  echo "[INFO] Re-running with sudo..."
  # Reconstruct -n flags for sudo rerun
  NFLAGS=()
  for n in "${NAMES[@]}"; do NFLAGS+=("-n" "$n"); done
  exec sudo -E bash "$0" "${NFLAGS[@]}" -o "$OUT_DIR" -d "$DAYS" ${FORCE:+-f}
fi

# Check openssl availability
if ! command -v openssl >/dev/null 2>&1; then
  echo "[ERROR] openssl not found. Please install it (e.g., apt-get install -y openssl)" 1>&2
  exit 1
fi

# Create output directory
mkdir -p "$OUT_DIR"
chmod 755 "$OUT_DIR"

CERT_PATH="$OUT_DIR/cert.pem"
KEY_PATH="$OUT_DIR/key.pem"
CFG_PATH="/tmp/frbot_ssl_$(date +%s).cnf"

backup_if_exists() {
  local path="$1"
  if [[ -f "$path" && $FORCE -eq 0 ]]; then
    local ts="$(date +%Y%m%d_%H%M%S)"
    local bak="${path}.${ts}.bak"
    echo "[INFO] Backing up existing $(basename "$path") to $bak"
    cp -f "$path" "$bak"
  fi
}

is_ip() {
  # Basic IPv4 detection
  local ip_re='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
  if [[ "$1" =~ $ip_re ]]; then
    return 0
  else
    return 1
  fi
}

# Deduplicate names and prepare SAN lists
declare -A added
uniq_names=()
for n in "${NAMES[@]}"; do
  if [[ -z "${added[$n]:-}" ]]; then
    added[$n]=1
    uniq_names+=("$n")
  fi
done

# Ensure localhost and 127.0.0.1 are present once
if [[ -z "${added[localhost]:-}" ]]; then
  uniq_names+=("localhost")
  added[localhost]=1
fi
if [[ -z "${added[127.0.0.1]:-}" ]]; then
  uniq_names+=("127.0.0.1")
  added[127.0.0.1]=1
fi

CN_NAME="${uniq_names[0]}"

# Build openssl config with SANs
{
  echo "[req]"
  echo "default_bits = 2048"
  echo "prompt = no"
  echo "default_md = sha256"
  echo "req_extensions = v3_req"
  echo "distinguished_name = dn"
  echo ""
  echo "[dn]"
  echo "CN = ${CN_NAME}"
  echo ""
  echo "[v3_req]"
  echo "subjectAltName = @alt_names"
  echo "keyUsage = keyEncipherment, dataEncipherment, digitalSignature"
  echo "extendedKeyUsage = serverAuth"
  echo ""
  echo "[alt_names]"
  dns_i=1
  ip_i=1
  for n in "${uniq_names[@]}"; do
    if is_ip "$n"; then
      echo "IP.${ip_i} = ${n}"
      ip_i=$((ip_i+1))
    else
      echo "DNS.${dns_i} = ${n}"
      dns_i=$((dns_i+1))
    fi
  done
} > "$CFG_PATH"

echo "[INFO] OpenSSL config written to $CFG_PATH"

# Backup existing files when not forcing
backup_if_exists "$CERT_PATH"
backup_if_exists "$KEY_PATH"

# Generate key and self-signed cert
openssl req \
  -x509 \
  -nodes \
  -newkey rsa:2048 \
  -keyout "$KEY_PATH" \
  -out "$CERT_PATH" \
  -days "$DAYS" \
  -config "$CFG_PATH" \
  -extensions v3_req

# Secure permissions
chmod 600 "$KEY_PATH"
chmod 644 "$CERT_PATH"

echo "[INFO] Generated:"
echo "  CERT: $CERT_PATH"
echo "  KEY : $KEY_PATH"

# Install system-wide environment variables for Uvicorn
PROFILE_D="/etc/profile.d/uvicorn_ssl.sh"
{
  echo "# Auto-generated by generate_ssl.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "export UVICORN_SSL_CERTFILE=\"$CERT_PATH\""
  echo "export UVICORN_SSL_KEYFILE=\"$KEY_PATH\""
} > "$PROFILE_D"
chmod 644 "$PROFILE_D"

echo "[INFO] Wrote env to $PROFILE_D"

echo "[INFO] To apply in current shell, run:"
echo "  source $PROFILE_D"

echo "[DONE] HTTPS cert/key created and environment variables installed."
