#!/bin/bash

mkdir fr_bot
cd fr_bot
git clone git@github.com:duong-sau/fr_bot.git
mv fr_bot code
mkdir data
mkdir logs

cd code
sudo apt-get update -y
sudo apt-get install python3-venv -y
python3 -m venv .linux_env
source .linux_env/bin/activate
pip install -r requirements.txt
