# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservices.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'microservices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13microservices.proto\x1a\x1cgoogle/protobuf/struct.proto\" \n\x0bPingMessage\x12\x11\n\tclient_id\x18\x01 \x01(\t\"5\n\x0cPingResponse\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"(\n\x13StartAndStopCommand\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9a\x01\n\x16MicroserviceController\x12#\n\x04Ping\x12\x0c.PingMessage\x1a\r.PingResponse\x12-\n\x0cStartService\x12\x14.StartAndStopCommand\x1a\x07.Result\x12,\n\x0bStopService\x12\x14.StartAndStopCommand\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGMESSAGE']._serialized_start=53
  _globals['_PINGMESSAGE']._serialized_end=85
  _globals['_PINGRESPONSE']._serialized_start=87
  _globals['_PINGRESPONSE']._serialized_end=140
  _globals['_STARTANDSTOPCOMMAND']._serialized_start=142
  _globals['_STARTANDSTOPCOMMAND']._serialized_end=182
  _globals['_RESULT']._serialized_start=184
  _globals['_RESULT']._serialized_end=209
  _globals['_MICROSERVICECONTROLLER']._serialized_start=212
  _globals['_MICROSERVICECONTROLLER']._serialized_end=366
# @@protoc_insertion_point(module_scope)
